Repository TheRealJackiBoi/java-deepdive-final, pull requests merged in 2023-09, with the labels that each got.

#3 Class diagram
  Documentation/ClassDiagram.puml
Labels: documentation

#2 Package setup 🙀
  .DS_Store
  src/main/java/org/dat3/Main.java
  src/main/java/org/dat3/config/HibernateConfig.java
  src/main/java/org/dat3/dao/CountryDAO.java
  src/main/java/org/dat3/dao/CurrencyDAO.java
  src/main/java/org/dat3/dao/ValueDAO.java
  src/main/java/org/dat3/dao/cruddao/CRUDDAO.java
  src/main/java/org/dat3/model/Country.java
  src/main/java/org/dat3/model/Currency.java
  src/main/java/org/dat3/model/Value.java
  src/main/java/org/dat3/utils/Fetcher.java
Labels: enhancement

#5 Fetcher made to interface and update to ClassDiagram🍻
  Documentation/ClassDiagram.puml
  src/main/java/org/dat3/utils/Fetcher.java
Labels: enhancement

#6 Generic dev - skulle hedde generic-dao
  src/main/java/org/dat3/dao/CountryDAO.java
  src/main/java/org/dat3/dao/CurrencyDAO.java
  src/main/java/org/dat3/dao/ValueDAO.java
  src/main/java/org/dat3/dao/cruddao/CRUDDAO.java
  src/main/java/org/dat3/dao/cruddao/DAO.java
  src/main/java/org/dat3/dao/cruddao/DAOInterface.java
Labels: good first issue

#9 Country fetcher
  .idea/compiler.xml
  src/main/java/org/dat3/Main.java
  src/main/java/org/dat3/dao/CurrencyDAO.java
  src/main/java/org/dat3/dao/cruddao/CRUDDAO.java
  src/main/java/org/dat3/model/Country.java
  src/main/java/org/dat3/model/Currency.java
  src/main/java/org/dat3/model/Value.java
  src/main/java/org/dat3/utils/CountryExtractor.java
  src/main/java/org/dat3/utils/CountryFetcher.java
  src/main/java/org/dat3/utils/Fetcher.java
  src/main/java/org/dat3/utils/HTTPUtils.java
Labels: enhancement

#11 Update Readme.md
  Readme.md
Labels: documentation

#14 check if country exists in db and update CountryDAO findById🦩
  src/main/java/org/dat3/dao/CountryDAO.java
  src/main/java/org/dat3/model/Country.java
  src/main/java/org/dat3/utils/CountryExtractor.java
Labels: enhancement

#15 only create currency if there is none or it doesn't match the country
  src/main/java/org/dat3/utils/CountryExtractor.java
Labels: enhancement

#16 Crudtests not working 🥋
  .idea/dataSources.xml
  src/test/java/org/dat3/dao/cruddao/DAOTest.java
Labels: help wanted

#18 RELATION SHIP BETWEEN VALUE AND CURRENCY WORKS!🥳
  .idea/dataSources.xml
  src/main/java/org/dat3/model/Currency.java
  src/main/java/org/dat3/utils/TradeExtractor.java
  src/test/java/org/dat3/dao/cruddao/DAOTest.java
Labels: enhancement

#20 Tradecalculator - finished and tested
  Documentation/ClassDiagram.puml
  src/main/java/org/dat3/dto/TradeDTO.java
  src/main/java/org/dat3/utils/TradeCalculator.java
  src/main/java/org/dat3/utils/TradeValueConverter.java
  src/test/java/org/dat3/utils/TradeCalculatorTest.java
Labels: enhancement

#19 added test for all CRUDS, added value.find method, added @setter 🤸🏼‍♀️
  src/main/java/org/dat3/dao/CurrencyDAO.java
  src/main/java/org/dat3/dao/ValueDAO.java
  src/main/java/org/dat3/model/Country.java
  src/main/java/org/dat3/model/Currency.java
  src/main/java/org/dat3/model/Value.java
  src/test/java/org/dat3/dao/cruddao/DAOTest.java
Labels: documentation

#24 Documentation
  Documentation/CodeStandard.md
  Documentation/DoD.md
  Readme.md
Labels: documentation

#29 Multithread
  src/main/java/org/dat3/Main.java
  src/main/java/org/dat3/config/ExecutorServiceConfig.java
  src/main/java/org/dat3/utils/CountryExtractor.java
  src/main/java/org/dat3/utils/TradeExtractor.java
Labels: enhancement

#32 Dev 👰🏼 merged 👨🏿‍🔬 into 🥵 main 🤾🏼
  .DS_Store
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/intellij-javadocs-4.0.1.xml
  .idea/misc.xml
  Documentation/ClassDiagram.png
  Documentation/ClassDiagram.puml
  Documentation/CodeStandard.md
  Documentation/DoD.md
  Documentation/DomainModel.png
  Documentation/DomainModel.puml
  Documentation/EER-Diagram.png
  Readme.md
  pom.xml
  src/main/java/org/dat3/Main.java
  src/main/java/org/dat3/config/ExecutorServiceConfig.java
  src/main/java/org/dat3/config/HibernateConfig.java
  src/main/java/org/dat3/dao/CountryDAO.java
  src/main/java/org/dat3/dao/CurrencyDAO.java
  src/main/java/org/dat3/dao/ValueDAO.java
  src/main/java/org/dat3/dao/cruddao/CRUDDAO.java
  src/main/java/org/dat3/dao/cruddao/DAO.java
  src/main/java/org/dat3/dao/cruddao/DAOInterface.java
  src/main/java/org/dat3/dto/TradeDTO.java
  src/main/java/org/dat3/model/Country.java
  src/main/java/org/dat3/model/Currency.java
  src/main/java/org/dat3/model/Value.java
  src/main/java/org/dat3/utils/CountryExtractor.java
  src/main/java/org/dat3/utils/CountryFetcher.java
  src/main/java/org/dat3/utils/Fetcher.java
  src/main/java/org/dat3/utils/HTTPUtils.java
  src/main/java/org/dat3/utils/TradeCalculator.java
  src/main/java/org/dat3/utils/TradeExtractor.java
  src/main/java/org/dat3/utils/TradeFetcher.java
  src/test/java/org/dat3/dao/cruddao/DAOTest.java
  src/test/java/org/dat3/dao/cruddao/HibernateConfigTEST.java
  src/test/java/org/dat3/utils/CountryExtractorTest.java
  src/test/java/org/dat3/utils/CountryFetcherTest.java
  src/test/java/org/dat3/utils/TradeCalculatorTest.java
  src/test/java/org/dat3/utils/TradeExtractorTest.java
  src/test/java/org/dat3/utils/TradeFetcherTest.java
  src/test/java/org/dat3/utils/testHTML.html
Labels: enhancement
